[package]
name = "timeout_estimator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bdays = "0.1.3"
chrono = "0.4.37"
clap = { version = "4.5.4", features = ["derive"] }
